### ISSUE TITLE
The link to Chinese version is invalid

### ISSUE THREAD

**Issue by taobyaaa** [remzi-arpacidusseau/ostep-translations#1]
Sorry! The URL you requested was not found on our server.
Is it Sunday between 4 and 8 PM (CST)?
If so, the server may be undergoing regularly scheduled downtime.

Otherwise, please contact the maintainer of the referring page and ask them to fix their link.
Thanks!

**Comment by mkmoisen** [comment]
Hi @taobyaaa 你找到了中文本版吗？

**Comment by remzi-arpacidusseau** [comment]
I will get to this soon - thanks!

**Comment by taobyaaa** [comment]
> Hi @taobyaaa 你找到了中文本版吗？

之前有个翻译项目https://github.com/EmbedXj/OperatingSystems.ThreeEasyPieces，但只是翻译了一部分，随着这本书的中译版《操作系统导论》的出版，那个翻译计划已经停止了。
另外，我简单翻看了下中译版本，质量一般，建议直接看英文原版。

**Comment by mkmoisen** [comment]
@taobyaaa 
现在中文本版好了：
https://github.com/remzi-arpacidusseau/ostep-translations/tree/master/chinese
