### ISSUE TITLE
Chinese Translation links are invalid

### ISSUE THREAD

**Issue by mkmoisen** [remzi-arpacidusseau/ostep-translations#2]
On the page for the Chinese translations: https://github.com/remzi-arpacidusseau/ostep-translations/tree/master/chinese

All of the links are invalid. For example, http://pages.cs.wisc.edu/~remzi/OSTEP/Chinese/13.pdf shows the following error:

    Computer Sciences Dept.
    Sorry! The URL you requested was not found on our server.
    
    Is it Sunday between 4 and 8 PM (CST)?
    If so, the server may be undergoing regularly scheduled downtime.
    
    Otherwise, please contact the maintainer of the referring page and ask them to fix their link.
    Thanks! 

It doesn't matter what time of day in CST it is, this message is always shown.

**Comment by remzi-arpacidusseau** [comment]
Fixed.

**Comment by mkmoisen** [comment]
@remzi-arpacidusseau epic; thank you!
